stages:
  - build
  - Test

build_project:
  stage: build
  script:
    - xcodebuild -scheme Testing in Xcode
  tags:
    - swift
    - testing

Feature Tests:
  stage: Test
  script: 
   - xcodebuild -scheme Testing in Xcode -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.4' test | xcpretty --color
  tags:
   - swift
   - testing
