stages:
    - Build

variables:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"

build_project:
  stage: Build
  script:
    - bundle install
    - bundle exec fastlane Testing in Xcode
  artifacts:
    path:
	- ./Testing in Xcode.ipa
  tags:
    - ios
    - xcode
