stages:
  - Build

build_project:
  stage: Build
  script:
    - xcodebuild clean -project Testing in Xcode.xcodeproj -scheme Testing in Xcode
    - xcodebuild test -project Testing in Xcode.xcodeproj -scheme Testing in Xcode
  tags:
    - ios
    - xcode
