stages:
  - Build

build_project:
  stage: Build
  script:
    - xcodebuild clean -project Testing in Xcode.xcodeproj -scheme Testing in Xcode | xcpretty
    - xcodebuild test -project Testing in Xcode.xcodeproj -scheme Testing in Xcode | xcpretty -c && exit ${PIPESTATUS[0]}
  tags:
    - swift
    - testing
