stages:
    - Build
    - Test

variables:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"

build_project:
  stage: Build
  script:
    - xcodebuild -project Testing\ in\ Xcode.xcodeproj -scheme Testing\ in\ Xcode clean
  tags:
    - ios
    - xcode

test_project:
  stage: Test
  script:
    - xcodebuild -project Testing\ in\ Xcode.xcodeproj -scheme Testing\ in\ Xcode test
  tags:
    - ios
    - xcode    
