stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project Testing in Xcode.xcodeproj -scheme Testing in Xcode | xcpretty
    - xcodebuild test -project Testing in Xcode.xcodeproj -scheme Testing in Xcode -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.4' | xcpretty -s
  tags:
    - swift
    - testing
